version: '3'

services:
  networkmap-backend:
    build: ./backend
    ports:
      - 8080:80
    env_file:
      - ./env/laravel.env
      - ./env/laravel.secret.env
    volumes:
      - backenduploads:/var/www/public/uploads
    links:
      - neo4j:neo4j
      - mysql:mysql
      - redis:redis
  networkmap-frontend:
    build: ./frontend
    ports:
      - 80:80
    volumes:
      - frontenduploads:/var/www/wordpress/wp-content/uploads
      - ./frontend/theme:/var/www/wordpress/wp-content/themes/networkmap
    links:
      - mysql:mysql
      - networkmap-backend:networkmap-backend
    env_file:
      - ./env/wordpress.env
      - ./env/wordpress.secret.env
  neo4j:
    image: neo4j:3.1.5
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j:/data
  mysql:
    image: mariadb:5
    ports:
      - 3306:3306
    env_file: 
      - ./env/mysql.env 
      - ./env/mysql.secret.env 
    # environment:
    #   - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - mysql2:/var/lib/mysql/
    # command:
    #   'mysqld --innodb-flush-method=fsync'
  redis:
    image: redis
    expose:
      - 6379
    volumes:
      - redis:/data

volumes:
  backenduploads:
  frontenduploads:
  neo4j:
  mysql2:
  redis:
